/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	readonly '/api/v1/operating-rooms': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get: operations['list'];
		readonly put?: never;
		readonly post: operations['create'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/bookings': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get: operations['list_1'];
		readonly put?: never;
		readonly post: operations['create_1'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/bookings/{id}/start': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['start'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/bookings/{id}/complete': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['complete'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/bookings/{id}/cancel': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['cancel'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/verify': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['verify'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/register': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['register'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/password/reset': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['resetPassword'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/password/forgot': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['forgotPassword'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/password/change': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['changePassword'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/passkeys/registration/finish': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['finishRegistration'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/passkeys/registration/begin': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['beginRegistration'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/passkeys/authentication/finish': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['finishAuthentication'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/passkeys/authentication/begin': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['beginAuthentication'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/logout': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['logout'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/login': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['login'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/invitation/preview': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['previewInvitation'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/invitation/accept': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post: operations['acceptInvitation'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/admin/invitations': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get: operations['list_2'];
		readonly put?: never;
		readonly post: operations['create_2'];
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/operating-rooms/{id}': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get: operations['get'];
		readonly put?: never;
		readonly post?: never;
		readonly delete: operations['archive'];
		readonly options?: never;
		readonly head?: never;
		readonly patch: operations['update'];
		readonly trace?: never;
	};
	readonly '/api/v1/clinic/settings': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get: operations['get_1'];
		readonly put?: never;
		readonly post?: never;
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch: operations['update_1'];
		readonly trace?: never;
	};
	readonly '/api/v1/bookings/{id}': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get: operations['get_2'];
		readonly put?: never;
		readonly post?: never;
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch: operations['update_2'];
		readonly trace?: never;
	};
	readonly '/api/v1/auth/passkeys/{id}': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post?: never;
		readonly delete: operations['revoke'];
		readonly options?: never;
		readonly head?: never;
		readonly patch: operations['rename'];
		readonly trace?: never;
	};
	readonly '/api/v1/admin/users/{id}': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post?: never;
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch: operations['patch'];
		readonly trace?: never;
	};
	readonly '/api/v1/users/surgeons': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get: operations['listSurgeons'];
		readonly put?: never;
		readonly post?: never;
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/schedule': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get: operations['day'];
		readonly put?: never;
		readonly post?: never;
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/events': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get: operations['subscribe'];
		readonly put?: never;
		readonly post?: never;
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/passkeys': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get: operations['list_3'];
		readonly put?: never;
		readonly post?: never;
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/auth/me': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get: operations['me'];
		readonly put?: never;
		readonly post?: never;
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/admin/users': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get: operations['list_4'];
		readonly put?: never;
		readonly post?: never;
		readonly delete?: never;
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
	readonly '/api/v1/admin/invitations/{id}': {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly get?: never;
		readonly put?: never;
		readonly post?: never;
		readonly delete: operations['revoke_1'];
		readonly options?: never;
		readonly head?: never;
		readonly patch?: never;
		readonly trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		readonly CreateOperatingRoomRequest: {
			readonly code: string;
			readonly name: string;
			readonly notes?: string;
		};
		readonly CreateBookingRequest: {
			/** Format: uuid */
			readonly operatingRoomId: string;
			/** Format: uuid */
			readonly surgeonId: string;
			/** Format: date-time */
			readonly startsAt: string;
			/** Format: date-time */
			readonly endsAt: string;
			readonly opType: string;
			readonly patientRef: string;
			readonly notes?: string;
		};
		readonly CancelBookingRequest: {
			readonly reason: string;
		};
		readonly VerifyRequest: {
			readonly token: string;
		};
		readonly RegisterRequest: {
			readonly email: string;
			readonly password: string;
			readonly displayName: string;
		};
		readonly ResetPasswordRequest: {
			readonly token: string;
			readonly newPassword: string;
		};
		readonly ForgotPasswordRequest: {
			readonly email: string;
		};
		readonly MessageResponse: {
			readonly message: string;
		};
		readonly ChangePasswordRequest: {
			readonly currentPassword: string;
			readonly newPassword: string;
		};
		readonly FinishRegistrationRequest: {
			readonly id: string;
			readonly attestationObject: string;
			readonly clientDataJSON: string;
			readonly transports?: readonly string[];
			readonly deviceName: string;
		};
		readonly AuthenticatorSelection: {
			readonly residentKey: string;
			readonly userVerification: string;
		};
		readonly BeginRegistrationResponse: {
			readonly challenge: string;
			readonly rp: components['schemas']['Rp'];
			readonly user: components['schemas']['UserInfo'];
			readonly pubKeyCredParams: readonly components['schemas']['PubKeyCredParam'][];
			/** Format: int64 */
			readonly timeout: number;
			readonly excludeCredentials: readonly components['schemas']['DescriptorRef'][];
			readonly authenticatorSelection: components['schemas']['AuthenticatorSelection'];
			readonly attestation: string;
		};
		readonly DescriptorRef: {
			readonly type: string;
			readonly id: string;
			readonly transports?: readonly string[];
		};
		readonly PubKeyCredParam: {
			readonly type: string;
			/** Format: int32 */
			readonly alg: number;
		};
		readonly Rp: {
			readonly id: string;
			readonly name: string;
		};
		readonly UserInfo: {
			readonly id: string;
			readonly name: string;
			readonly displayName: string;
		};
		readonly FinishAuthenticationRequest: {
			readonly handle: string;
			readonly id: string;
			readonly authenticatorData: string;
			readonly clientDataJSON: string;
			readonly signature: string;
			readonly userHandle?: string;
		};
		readonly BeginAuthenticationRequest: {
			readonly email: string;
		};
		readonly BeginAuthenticationResponse: {
			readonly handle: string;
			readonly challenge: string;
			readonly rpId: string;
			/** Format: int64 */
			readonly timeout: number;
			readonly userVerification: string;
			readonly allowCredentials: readonly components['schemas']['DescriptorRef'][];
		};
		readonly LoginRequest: {
			readonly email: string;
			readonly password: string;
		};
		readonly InvitationPreviewRequest: {
			readonly token: string;
		};
		readonly AcceptInvitationRequest: {
			readonly token: string;
			readonly password: string;
			readonly displayName: string;
		};
		readonly CreateInvitationRequest: {
			readonly email: string;
			/** @enum {string} */
			readonly role: 'ADMIN' | 'MANAGER' | 'STAFF';
			readonly isSurgeon: boolean;
			/** @enum {string} */
			readonly specialty?:
				| 'CARDIOLOGY'
				| 'ORTHOPEDICS'
				| 'GENERAL'
				| 'NEUROSURGERY'
				| 'OPHTHALMOLOGY';
		};
		readonly UpdateOperatingRoomRequest: {
			readonly name: string;
			readonly notes: string;
			/** @enum {string} */
			readonly status: 'ACTIVE' | 'MAINTENANCE' | 'RETIRED';
		};
		readonly UpdateClinicSettingsRequest: {
			readonly name: string;
			readonly timezone: string;
			/** @example 14:30:00 */
			readonly workingHoursStart: string;
			/** @example 14:30:00 */
			readonly workingHoursEnd: string;
			/** Format: int32 */
			readonly defaultBookingMinutes: number;
		};
		readonly UpdateBookingRequest: {
			/** Format: uuid */
			readonly operatingRoomId: string;
			/** Format: uuid */
			readonly surgeonId: string;
			/** Format: date-time */
			readonly startsAt: string;
			/** Format: date-time */
			readonly endsAt: string;
			readonly opType: string;
			readonly notes: string;
		};
		readonly RenamePasskeyRequest: {
			readonly deviceName: string;
		};
		readonly UpdateUserAdminRequest: {
			/** @enum {string} */
			readonly role: 'ADMIN' | 'MANAGER' | 'STAFF';
			readonly isSurgeon: boolean;
			/** @enum {string} */
			readonly specialty:
				| 'CARDIOLOGY'
				| 'ORTHOPEDICS'
				| 'GENERAL'
				| 'NEUROSURGERY'
				| 'OPHTHALMOLOGY';
			/** @enum {string} */
			readonly status: 'ACTIVE' | 'DISABLED';
		};
		readonly SurgeonSummaryDto: {
			/** Format: uuid */
			readonly id: string;
			readonly displayName: string;
			/** @enum {string} */
			readonly specialty:
				| 'CARDIOLOGY'
				| 'ORTHOPEDICS'
				| 'GENERAL'
				| 'NEUROSURGERY'
				| 'OPHTHALMOLOGY';
		};
		readonly BookingDto: {
			/** Format: uuid */
			readonly id: string;
			/** Format: uuid */
			readonly operatingRoomId: string;
			/** Format: uuid */
			readonly surgeonId: string;
			/** Format: uuid */
			readonly createdById: string;
			/** Format: date-time */
			readonly startsAt: string;
			/** Format: date-time */
			readonly endsAt: string;
			readonly opType: string;
			readonly patientRef: string;
			/** @enum {string} */
			readonly status: 'SCHEDULED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
			readonly notes?: string;
			/** Format: date-time */
			readonly createdAt: string;
			/** Format: date-time */
			readonly updatedAt: string;
		};
		readonly OperatingRoomScheduleDto: {
			/** Format: uuid */
			readonly id: string;
			readonly code: string;
			readonly name: string;
			/** @enum {string} */
			readonly status: 'ACTIVE' | 'MAINTENANCE' | 'RETIRED';
			readonly bookings: readonly components['schemas']['BookingDto'][];
		};
		readonly ScheduleDto: {
			/** Format: date */
			readonly date: string;
			readonly timezone: string;
			readonly operatingRooms: readonly components['schemas']['OperatingRoomScheduleDto'][];
		};
		readonly OperatingRoomDto: {
			/** Format: uuid */
			readonly id: string;
			readonly code: string;
			readonly name: string;
			/** @enum {string} */
			readonly status: 'ACTIVE' | 'MAINTENANCE' | 'RETIRED';
			readonly notes?: string;
			/** Format: date-time */
			readonly createdAt: string;
			/** Format: date-time */
			readonly updatedAt: string;
		};
		readonly SseEmitter: {
			/** Format: int64 */
			readonly timeout: number;
		};
		readonly ClinicSettingsDto: {
			readonly name: string;
			readonly timezone: string;
			/** @example 14:30:00 */
			readonly workingHoursStart: string;
			/** @example 14:30:00 */
			readonly workingHoursEnd: string;
			/** Format: int32 */
			readonly defaultBookingMinutes: number;
		};
		readonly PasskeySummary: {
			/** Format: uuid */
			readonly id: string;
			readonly deviceName: string;
			/** Format: date-time */
			readonly createdAt: string;
			/** Format: date-time */
			readonly lastUsedAt?: string;
		};
		readonly UserResponse: {
			/** Format: uuid */
			readonly id: string;
			readonly email: string;
			readonly displayName: string;
			/** @enum {string} */
			readonly role: 'ADMIN' | 'MANAGER' | 'STAFF';
			readonly isSurgeon: boolean;
			/** @enum {string} */
			readonly specialty?:
				| 'CARDIOLOGY'
				| 'ORTHOPEDICS'
				| 'GENERAL'
				| 'NEUROSURGERY'
				| 'OPHTHALMOLOGY';
			/** @enum {string} */
			readonly status: 'ACTIVE' | 'DISABLED';
			/** Format: date-time */
			readonly emailVerifiedAt?: string;
			/** Format: date-time */
			readonly createdAt: string;
		};
		readonly AdminUserListQuery: {
			readonly q?: string;
			/** @enum {string} */
			readonly role?: 'ADMIN' | 'MANAGER' | 'STAFF';
			readonly isSurgeon?: boolean;
			/** @enum {string} */
			readonly status?: 'ACTIVE' | 'DISABLED';
			/** Format: int32 */
			readonly page: number;
			/** Format: int32 */
			readonly pageSize: number;
		};
		readonly AdminUserDto: {
			/** Format: uuid */
			readonly id: string;
			readonly email: string;
			readonly displayName: string;
			/** @enum {string} */
			readonly role: 'ADMIN' | 'MANAGER' | 'STAFF';
			readonly isSurgeon: boolean;
			/** @enum {string} */
			readonly specialty?:
				| 'CARDIOLOGY'
				| 'ORTHOPEDICS'
				| 'GENERAL'
				| 'NEUROSURGERY'
				| 'OPHTHALMOLOGY';
			/** @enum {string} */
			readonly status: 'ACTIVE' | 'DISABLED';
			/** Format: date-time */
			readonly emailVerifiedAt?: string;
			/** Format: date-time */
			readonly createdAt: string;
		};
		readonly AdminUserPageDto: {
			readonly items: readonly components['schemas']['AdminUserDto'][];
			/** Format: int32 */
			readonly page: number;
			/** Format: int32 */
			readonly pageSize: number;
			/** Format: int32 */
			readonly total: number;
		};
		readonly InvitationDto: {
			/** Format: uuid */
			readonly id: string;
			readonly email: string;
			/** @enum {string} */
			readonly role: 'ADMIN' | 'MANAGER' | 'STAFF';
			readonly isSurgeon: boolean;
			/** @enum {string} */
			readonly specialty?:
				| 'CARDIOLOGY'
				| 'ORTHOPEDICS'
				| 'GENERAL'
				| 'NEUROSURGERY'
				| 'OPHTHALMOLOGY';
			/** Format: uuid */
			readonly issuedById: string;
			/** Format: date-time */
			readonly issuedAt: string;
			/** Format: date-time */
			readonly expiresAt: string;
			/** Format: date-time */
			readonly acceptedAt?: string;
			/** Format: date-time */
			readonly revokedAt?: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	readonly list: {
		readonly parameters: {
			readonly query?: {
				readonly includeRetired?: boolean;
			};
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': readonly components['schemas']['OperatingRoomDto'][];
				};
			};
		};
	};
	readonly create: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['CreateOperatingRoomRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly list_1: {
		readonly parameters: {
			readonly query?: {
				readonly operatingRoomId?: string;
				readonly surgeonId?: string;
				readonly from?: string;
				readonly to?: string;
				readonly status?: 'SCHEDULED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
			};
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': readonly components['schemas']['BookingDto'][];
				};
			};
		};
	};
	readonly create_1: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['CreateBookingRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly start: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path: {
				readonly id: string;
			};
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly complete: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path: {
				readonly id: string;
			};
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly cancel: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path: {
				readonly id: string;
			};
			readonly cookie?: never;
		};
		readonly requestBody?: {
			readonly content: {
				readonly 'application/json': components['schemas']['CancelBookingRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly verify: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['VerifyRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly register: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['RegisterRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly resetPassword: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['ResetPasswordRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly forgotPassword: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['ForgotPasswordRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': components['schemas']['MessageResponse'];
				};
			};
		};
	};
	readonly changePassword: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['ChangePasswordRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly finishRegistration: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['FinishRegistrationRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly beginRegistration: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': components['schemas']['BeginRegistrationResponse'];
				};
			};
		};
	};
	readonly finishAuthentication: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['FinishAuthenticationRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly beginAuthentication: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['BeginAuthenticationRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': components['schemas']['BeginAuthenticationResponse'];
				};
			};
		};
	};
	readonly logout: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': components['schemas']['MessageResponse'];
				};
			};
		};
	};
	readonly login: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['LoginRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly previewInvitation: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['InvitationPreviewRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly acceptInvitation: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['AcceptInvitationRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly list_2: {
		readonly parameters: {
			readonly query?: {
				readonly includeHistory?: boolean;
			};
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': readonly components['schemas']['InvitationDto'][];
				};
			};
		};
	};
	readonly create_2: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['CreateInvitationRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly get: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path: {
				readonly id: string;
			};
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly archive: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path: {
				readonly id: string;
			};
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly update: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path: {
				readonly id: string;
			};
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['UpdateOperatingRoomRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly get_1: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': components['schemas']['ClinicSettingsDto'];
				};
			};
		};
	};
	readonly update_1: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['UpdateClinicSettingsRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly get_2: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path: {
				readonly id: string;
			};
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly update_2: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path: {
				readonly id: string;
			};
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['UpdateBookingRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly revoke: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path: {
				readonly id: string;
			};
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description No Content */
			readonly 204: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly rename: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path: {
				readonly id: string;
			};
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['RenamePasskeyRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly patch: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path: {
				readonly id: string;
			};
			readonly cookie?: never;
		};
		readonly requestBody: {
			readonly content: {
				readonly 'application/json': components['schemas']['UpdateUserAdminRequest'];
			};
		};
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
	readonly listSurgeons: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': readonly components['schemas']['SurgeonSummaryDto'][];
				};
			};
		};
	};
	readonly day: {
		readonly parameters: {
			readonly query?: {
				readonly date?: string;
				readonly includeMaintenance?: boolean;
			};
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': components['schemas']['ScheduleDto'];
				};
			};
		};
	};
	readonly subscribe: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly 'text/event-stream': components['schemas']['SseEmitter'];
				};
			};
		};
	};
	readonly list_3: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': readonly components['schemas']['PasskeySummary'][];
				};
			};
		};
	};
	readonly me: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': components['schemas']['UserResponse'];
				};
			};
		};
	};
	readonly list_4: {
		readonly parameters: {
			readonly query: {
				readonly query: components['schemas']['AdminUserListQuery'];
			};
			readonly header?: never;
			readonly path?: never;
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': components['schemas']['AdminUserPageDto'];
				};
			};
		};
	};
	readonly revoke_1: {
		readonly parameters: {
			readonly query?: never;
			readonly header?: never;
			readonly path: {
				readonly id: string;
			};
			readonly cookie?: never;
		};
		readonly requestBody?: never;
		readonly responses: {
			/** @description OK */
			readonly 200: {
				headers: {
					readonly [name: string]: unknown;
				};
				content: {
					readonly '*/*': Record<string, never>;
				};
			};
		};
	};
}
