import { type ClassValue, clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

/** Compose Tailwind class lists, deduplicating conflicts. */
export function cn(...inputs: ClassValue[]): string {
	return twMerge(clsx(inputs));
}

/* -----------------------------------------------------------------------------
 * shadcn-svelte type helpers
 *
 * These are the canonical helper types every component generated by
 * `pnpm dlx shadcn-svelte add ...` imports. We re-export them from here so
 * the generated source compiles without modification.
 * -------------------------------------------------------------------------- */

export type WithElementRef<T, U extends HTMLElement = HTMLElement> = T & {
	ref?: U | null;
};

export type WithoutChild<T> = T extends { child?: unknown } ? Omit<T, 'child'> : T;

export type WithoutChildren<T> = T extends { children?: unknown } ? Omit<T, 'children'> : T;

export type WithoutChildrenOrChild<T> = WithoutChildren<WithoutChild<T>>;
